### ISSUE TITLE
Support deeper sub-styles nesting.

### ISSUE THREAD

**Issue by lllShamanlll** [Jarzka/stylefy#1]
It can be usefull to have more than one level of sub-styles nesting.
i.e.
```clojure
(def control-style {::stylefy/sub-styles
                    {:button {::stylefy/sub-styles
                              {:icon { ... }}}}})

...

(use-sub-style control-style :button :icon)

```

**Comment by lllShamanlll** [comment]
Something like that will solve the problem in common way.
```clojure
(defn sub-style [style & seq]
    (if (empty? seq)
         style
         (recur (get (:stylefy.core/sub-styles style) (first seq)) (rest seq)))

(use-style (sub-style control-style :button :icon))
```
And will allow to merge nested styles also

```clojure
(use-style (merge (sub-style control-style :button :icon)) { ... })
```

**Comment by Jarzka** [comment]
I was thinking about adding a support for deeper sub-style nesting, but I gave up because if one needs more than one level of sub-style nesting, the style (and the component) is probably going to be too large and needs to be split into smaller parts.

HOWEVER, I kinda like your approach of using deeper level of sub-styles. I'll take a closer look at your pull request when I have time. :)

**Comment by Jarzka** [comment]
Support for deeper sub-styles has been added in version 0.7.2 without making any API breaking changes.
