### ISSUE TITLE
A way to convert to inline styles only?

### ISSUE THREAD

**Issue by nijk** [Jarzka/stylefy#28]
I have a use case where the Stylefy re-render causes issues with a JS tooltip dependency, the placement is miscalculated when calling `(use-style ...)`.

I'm wondering if there is a workaround available by requiring in a Stylefy function that will parse the Garden values and give me back a style map that can be passed directly to Hiccup?

**Comment by Jarzka** [comment]
I think I cannot understand your case without a code example.

Currently the function which is used to parse Garden units inside a style map is not part of stylefy's public API (since it should not really be needed). However, you can take a look at its implementation at stylefy.impl.utils namespace.

By the way, I'm on holiday now, so this is all info I can give you quickly right now. 😎

**Comment by nijk** [comment]
Thanks @Jarzka I've been digging into Garden a bit as I realised after posting this issue that it is probably a Garden question. Enjoy your holiday!
