### ISSUE TITLE
Readable class names in development

### ISSUE THREAD

**Issue by lsnape** [Jarzka/stylefy#30]
Hi 👋,

It would be really helpful if stylefy could toggle on human-readable class names in development. I often find myself staring at the DOM and the hashed stylefy class names, not knowing what I'm looking at!

Perhaps replacing `_stylefy_703018772` with `_masthead_703018772` would be the way to go? We could pass a kv pair `:stylefy/classname :masthead` to `use-style`. Maybe there is a more elegant solution.

Thanks for taking the time to create this library.

Luke

**Comment by Jarzka** [comment]
Hello 👋

Yes, it would be possible to allow the user of the library to choose the prefix name for the generated stylefy classes when calling `use-style`. We could also turn this feature off, if needed, in the init function's options map, for example like this:
`(stylefy/init {use-custom-class-prefix? false}`

This idea has been on my TODO list for some time, but I haven't implemented it since no-one has requested it. Until now. :)

However, this feature also requires the effort to name your style maps. The beautify of stylefy is that you do not need to name your style maps / classes, you can simply use style maps when needed and stylefy generates the class names automatically. Most of the time, there should be even no need to take a look at the autogenerated class names. If we start to name the style maps, it kinda defeats this benefit, even if it's done only for debugging purposes. Still, naming style maps would be completely optional, you could enter custom prefix if you wish, so perhaps this feature would still be useful?

Thanks for using this library. :-)

**Comment by lsnape** [comment]
I see what you mean. If all styles are passed in "anonymously" then of course it's extra work for the developer to add `::stylefy/class-prefix` everywhere.

Our usage differs slightly in that styles are defined in a hashmap elsewhere in the code, like this:

``` clojure
{:masthead {:theme-1 {:background-color :black}} :theme-2 {:background-color :blue}
 ...
}
```
Of course, we're taking advantage of `def`'ing styles, sharing and transforming them before constructing the style map – Clojure FTW!

We close over `use-style` with this map so we can select the style we need. It allows us to select the style by keyword _and_ theme at runtime. In our case, it's very little work to set the class prefix because the name of the style passed in to our wrapped version of `use-style` can be used.

I do get your point that enforcing upfront naming of styles makes stylefy's class name assignment redundant – and for a moment it had me questioning whether we were doing the right thing! But I fail to see for any non-trivial application why you wouldn't want to organise your styles by name according to the domain you're working in. Unless I'm missing something?

**Comment by Jarzka** [comment]
I think this feature could be implemented using the spec below:

- Add support for a new namespaced keyword ::stylefy/class-prefix. If this keyword is found in the style map when calling `use-style`, then the value of the keyword should be used as the prefix name of the class, instead of the default __stylefy__. The value of the keyword is assumed to be a string, any other value should raise an error.
- All custom prefixes can be turned off in the init function, like this: `(stylefy/init {:use-custom-class-prefix? false}`. If option map not used, `:use-custom-class-prefix?` is not found or the value is nil, this option should be true by default.
- Add test in which the custom prefix is used
- All current tests should pass.

If someone likes to implement this, feel free to send me PR. If not, I'm glad to implement this by myself at some point. If anyone, me included, starts working on this, please inform in this thread so that no duplicate work is done.

**Comment by lsnape** [comment]
Sounds good to me! I'll let you know if I pick this up.

Should we allow keywords and strings as class prefixes? IIRC reagent handles class names as keywords.
