### ISSUE TITLE
Error when combining stylefy.core/use-style with garden.def/defcssfn

### ISSUE THREAD

**Issue by wolfgangshilei** [Jarzka/stylefy#34]
**Environment:**
[garden  "1.3.6"]
[stylefy "1.11.0"]

**Browser:**
Google Chrome
Version 71.0.3578.98 (Official Build) (64-bit)

**Description:**
I have the following css function definition:
```
(garde.def/defcssfn url)
```
I use this function inside a css rule and then use stylefy/use-style to render it. The Hiccup is as below:
```
[:div (stylefy/use-style {:background (url "/some-url.jpeg")})]
```

**Expected behavior:**
Correctly rendering with the specified css rule.

**Actually behavior:**
```
A crash occurrs. The first a few lines of the crash log is copied below:
core.cljs:316 Uncaught Error: No protocol method IKVReduce.-kv-reduce defined for type : [object Object]
    at Object.cljs$core$missing_protocol [as missing_protocol] (core.cljs:316)
    at Object.cljs$core$_kv_reduce [as _kv_reduce] (core.cljs:697)
    at cljs$core$reduce_kv (core.cljs:2543)
    at reagent$impl$template$convert_prop_value (template.cljs?rel=1549179340604:67)
    at reagent$impl$template$kv_conv (template.cljs?rel=1549179340604:62)
    at core.cljs:7095
    at Object.cljs$core$inode_kv_reduce [as inode_kv_reduce] (core.cljs:7099)
    at Object.kv_reduce (core.cljs:7339)
```

**Further information that may be useful.**
1. If the element with the style in question is not displayed on the page in the first place (e.g. styled with display: none), the crash described above occurs too. However, after a refreshing of the page, the crash doesn't occur any more, and everything works as expected, including displaying the element in question. However if I delete the localStorage at this stage, the crash reappears.

2. I have also posted an issue on the Garden project that is possibly linked to this one:
[https://github.com/noprompt/garden/issues/170
](https://github.com/noprompt/garden/issues/170)
Thank you for your help.

**Comment by Jarzka** [comment]
Thank you for this detailed bug report. I'll take a closer look in a couple of days.

A workaround for this is to define the background property value simply as string:

```
[:div (stylefy/use-style {:background "url('/some-url.jpeg')"})]
```

**Comment by wolfgangshilei** [comment]
Thank you for the prompt reply. 
BTW, I am aware of the workaround but appreciate your note anyway.
Cheers.

**Comment by Jarzka** [comment]
I can confirm that this problem does exist, I was able to reproduce it. Without cache, it repeats every time, and with cache, it repeats the first time and after that, it is rendered correctly, just as you mentioned. Seems weird. However, at this point, I believe this bug is not caused by stylefy. I did not see anything suspicious related to stylefy in the call stack, and if you replace the **use-style** call with a regular CSS inline style definition, the bug still repeats:

`[:div {:style {:background (url "/some-url.jpeg")}}]`

As you mentioned in the issue posted on the Garden project, the macro does not behave as you would expect, so maybe it has something to do with it?

**Comment by wolfgangshilei** [comment]
Thanks for your investigations and feedback.
Could you please share the steps to reproduce the bug with only Garden?

**Comment by Jarzka** [comment]
I just took the example project from stylefy and did the following:

1) Remove every CLJS file except main.cljs
2) In the example project's project.clj file, make sure stylefy's sources are not included:
`:source-paths ["src"]`
3) Replace the main.cljs with the following:

```
(ns stylefy.examples.main
  (:require [reagent.core :as r]
            [cljs.core.async :refer [<! timeout]]
            [garden.core :as garden])
  (:require-macros [cljs.core.async.macros :refer [go]]
                   [garden.def :refer [defcssfn]]))

(garden.def/defcssfn url)

(defn- main []
  [:div {:style {:background (url "/some-url.jpeg")}}])

(defn ^:export start []
  (r/render main (.getElementById js/document "app")))
```

I think this proves that this is not caused by stylefy, as this bug happens even if stylefy's code is not included in the example project.

**Comment by wolfgangshilei** [comment]
I am no expert of Garden, but I doubt that functions defined by defcssfn should be used directly in the inline styles as being demostrated in the above code snippet. So while the code above indeed can reproduce the bug, my guess is that it is because the cssfunction is used in an unintended manner, though the error itself is still baffling enough.

When it comes to stylefy, however, the styles should be compiled first, the error should thus never happen exactly the same as it does in the "only Garden" scenario. It hence leads to me to guess that stylefy does not compile cssfunctions. Then I found the following workaround:

```
[:div {:style {:background (garden.compiler/render-css (url "/some-url.jpeg"))}}]
```
Quick test results show that this eliminates the crash. 

I my opinion, CSSFunction compilation should better be handled by stylefy (as it has been done today for CSSColor and CSSUnit). How do you think about it?

**Comment by Jarzka** [comment]
Good point, I probably have take another look at this.

However, I will soon be on vacation a week so it might take some time to get back to this. But of course, anyone is free to take a look at this and send me a PR if a solution is found. Otherwise, I'll take a look at this at some point after my vocation.

**Comment by Jarzka** [comment]
I can admit that I was wrong: indeed this is a problem in stylefy, and the problem is just what you said: CSSColor and CSSUnit are converted properly but CSSFunction is not. Luckily this quick to fix and I can do it before my vocation. I will soon release a beta build in which this bug is fixed.

**Comment by Jarzka** [comment]
1.12.0-beta1 is now released and should fix this issue. Also, it updates Garden to the latest version.

Here is my PR:
https://github.com/Jarzka/stylefy/pull/35

If no problems are found, I will mark this as stable in a week or two.

**Comment by wolfgangshilei** [comment]
I have tested `1.12.0-beta1` today concerning this ticket, and it indeed has fixed the bug. Thank you.

There is one last gotcha I found during my test concerning garden's defcssfn, though I don't think it has anything to do with Stylefy and I think it is an edge case. 

```
(macroexpand '(defcssfn url))
=> (def url
       ( clojure.core/fn ( [ & args ] ( garden.types.CSSFunction. "url" args ) ) ))
```

So at runtime the module that declares url with defcssfn must have knowledge about garden.types.CSSFunction. This is normal when working directly with Garden because it is likely that other Garden module will be required.

But when combining Garden with Stylefy, chance it is that no extra garden module will be required  (this has been my case):
```
(ns some-styles-module
  (:require-macros [garden.def :refer [defcssfn]]))
(defcssfn url)
(def some-style {:background (url "some-url")})
```

then there will be an error at runtime every time the page is refreshed
```
Uncaught ReferenceError: garden is not defined
    at mine_sweep$ui$record$styles$url__delegate (styles.cljs?rel=1550297849965:8)
    at mine_sweep$ui$record$styles$url (styles.cljs?rel=1550297849965:8)
    at styles.cljs?rel=1550297849965:29
```
The fix is simple: in the ns declaration form, declare a garden dependency explicitly (`(:require [garden.core])`.

I don't think Stylefy has anything to do with this issue, but do you think it is better to add a line of note in the documentation, to avoid possible future confusions?

And have a nice vacation.

**Comment by Jarzka** [comment]
Hello, I'm back from my vacation!

Yes, I also believe this case is related to Garden and it should be their responsibility to document it. However, it probably won't hurt anyone if we also mention this in stylefy's documentation. The README file and its Garden units section would be a natural place for this, since it's the only place where the usage of Garden units is ever mentioned. Thanks for pointing this out.

**Comment by Jarzka** [comment]
1.12.0 is now out as stable release.
