### ISSUE TITLE
Support for class names as keywords

### ISSUE THREAD

**Issue by paintparty** [Jarzka/stylefy#44]
Thanks for making **Stylefy**!
Really great project.

In order to maintain feature parity with reagent, would it be possible to support the following syntax in the second (html attributes) argument to `use-style`?

```Clojure
(use-style
    {:color "red"}               
    {:class :some-class})
```

And also a vector of keywords:
```Clojure
(use-style
    {:color "red"}               
    {:class [:some-class :some-other-class]})
```

**Comment by Jarzka** [comment]
This syntax looks convenient. However, the original idea of the second param was to pass the attributes directy to HTML, and ever since no-one has asked me to implement feature parity with Reagent. Thus, I'm not sure if it's something people are looking forward to. On the other hand, adding support for Reagent syntax should not be hard and as far as I know, should not break existing projects using stylefy.

I have to think about this. In the meantime, if you truly want feature parity with Reagent, you can always create your own wrapper for the second argument (or perhaps for the whole use-style function) which handles the Reagent syntax.

**Comment by Jarzka** [comment]
Glad you find stylefy useful.

I gave an answer to this, but I had to re-check it and it was partially incorrect, so I deleted it. Here is the new answer:

Yes, if this syntax works in Hiccup & Reagent, it should work in stylefy when you call `use-style`. Now it does not, and here is why:

Originally, the second param of `use-style` only accepted a map with a special keyword of `::with-classes`. Later, I changed the implementation of the second param so that the whole map contains HTML attributes. However, since some people had already used `::with-classes`, I had to implement support for it. Thus, how stylefy handles `:class` is that it combines both `:class` and `::with-classes`. In this combination, the richer syntax support of Reagent seems to be lost.

I think, at this point, it would be time to deprecate `::with-classes` once and for all, i.e. remove it completely and log a warning if people use it. The contents of `:class` would be used as it is and all Reagent syntax would be supported.

**Comment by Jarzka** [comment]
I forgot that `::with-styles` is still valid in style map, so we have to combine it with `:class` anyway. But maybe we can still add manual support for passing keywords and vector of keywords to `:class`. I'm planning on adding this support in the next version.

**Comment by paintparty** [comment]
Thanks!

**Comment by Jarzka** [comment]
This feature is now implemented in the latest release candidate version: `2.0.0-rc.2`

It should be stable, but I do not encourage you to use it in production just yet.

**Comment by paintparty** [comment]
Thanks for the quick turnaround!!
