### ISSUE TITLE
Getting Invalid DOM property `class`. Did you mean `className`?

### ISSUE THREAD

**Issue by pragyansden** [Jarzka/stylefy#49]
I am getting 

```
Invalid DOM property `class`. Did you mean `className`?
```
Warning while using stylefy. Is there a way I can rename this or fix this in my application?

**Comment by Jarzka** [comment]
This error does not come from stylefy. Instead, it's a React feature. React does not accept `class` property name, but wants `className` instead. Reagent, however, does not have such limitation.

Are you sure you are using Reagent in your project? You should be able to create HTML elements with `class` property with or without using stylefy.

**Comment by pragyansden** [comment]
I am trying to use fulcro with stylefy. I am trying to figure out is there any workaround for this issue?

**Comment by Jarzka** [comment]
I'm not familiar with fulcro, but if I'm right it uses React directly instead of Reagent. stylefy requires Reagent because the asyncronous style generation depends on Reagent atoms. Thus, currently there is no workaround for this.

There has been some discussion in the past of making stylefy Reagent free. Technically this is possible, but not without sacrifing some rendering speed.

**Comment by pragyansden** [comment]
OK. I will try out something else. Thanks a lot for the help. :)
