### ISSUE TITLE
Custom Tag styles [was: CSS reset]

### ISSUE THREAD

**Issue by polymeris** [Jarzka/stylefy#8]
What's the best way to declare a basic starting point/CSS reset?

One option would be to have a function analogous to `stylefy/class`, `stylefy/tag`, and do something like:

```
(stylefy/tag "html" {:border 0, :padding 0})
```

**Comment by Jarzka** [comment]
Currently the easiest way to solve this problem is to use some CSS reset frameowork, just put it in its own `style` tag before stylefy's own `style` tags, and it should work.

`stylefy/tag` sounds a good way to solve this problem directly with stylefy. Feel free to implement it and see how it would work (just remember to add a test for it and add an example in the examples project & README.md). I can also add it on the TODO list can implement it on my own at some point.

**Comment by polymeris** [comment]
The first option partially defeats the point of using this library, so I'll look into the `stylefy/tag` solution during the week.

**Comment by Jarzka** [comment]
Alright. Send me a PR when you're ready. :)

**Comment by polymeris** [comment]
See PR #9

**Comment by Jarzka** [comment]
I will take a look at it soon, hopefully tomorrow.

**Comment by Jarzka** [comment]
Very nice PR! I changed the base branch and merged. I'm going to include this new feature in the next release of stylefy, along with one minor bug fix. It will be released in the coming days.

Thanks for implementing this feature. 👍
